Includes new params within difference arr
othercodes/connect-processors-toolkit pull request #1
Opened 2022-03-25 12:31 UTC by JosePaniagua7

Add function to detect when new params are present and a request updated is try. This change is requested to be introduced since zip function will truncate all those parameters that have no correspondence, so, new params will be lost and difference will remain with 0 length and updated_parameters_request to connect will be skipped.

2022-03-27 17:27 UTC, othercodes requested changes
What is the purpose of the `connect/processors_toolkit/requests/custom_event.py` file?

2022-03-28 07:26 UTC, JosePaniagua7 commented
Sorry, my bad. I added a file for a new mixin implementation but added it in the wrong commit. The file has been removed from this pull request.

2022-03-28 09:52 UTC, othercodes approved these changes

2022-03-28 10:12 UTC, othercodes approved these changes

2022-03-28 10:22 UTC, othercodes approved these changes

2022-03-28 10:24 UTC, merged